# Generated by Django 4.0.2 on 2024-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('X', 'X'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin')], max_length=30)),
                ('Link', models.CharField(max_length=150)),
            ],
        ),
    ]
