# Generated by Django 4.0.2 on 2024-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_socialmedias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('X', 'X'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin')], max_length=30)),
                ('Post', models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('X', 'X'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin')], max_length=30)),
                ('description', models.TextField()),
                ('ProfilePic', models.ImageField(upload_to='Testimonial')),
            ],
        ),
    ]
