# Generated by Django 4.0.2 on 2024-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_alter_testimonial_post_alter_testimonial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strategy_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('IconsImage', models.ImageField(upload_to='Strategy_Icon')),
            ],
        ),
    ]
