# Generated by Django 4.0.2 on 2024-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0005_strategie'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategie',
            name='visual1',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='strategie',
            name='visual2',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='strategie',
            name='visual3',
            field=models.CharField(default='3', max_length=100),
        ),
        migrations.AddField(
            model_name='strategie',
            name='visual4',
            field=models.CharField(default='4', max_length=100),
        ),
    ]
