# Generated by Django 5.0.1 on 2024-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_strategie_visual1_strategie_visual2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webiniar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Webiniar_name', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=30)),
                ('Webiniar_short_desc', models.TextField()),
                ('Webiniar_image', models.ImageField(upload_to='webiniar')),
                ('price', models.CharField(max_length=10)),
                ('Author_name', models.CharField(max_length=30)),
                ('about_author', models.TextField()),
                ('what_you_learn1', models.TextField(null=True)),
                ('what_you_learn2', models.TextField(null=True)),
                ('what_you_learn3', models.TextField(null=True)),
                ('what_you_learn4', models.TextField(null=True)),
                ('what_you_learn5', models.TextField(null=True)),
                ('what_you_learn_desc', models.TextField(null=True)),
                ('class_for1', models.TextField(null=True)),
                ('class_for_desc', models.TextField(null=True)),
                ('Webiniar_time', models.CharField(max_length=30)),
                ('Webiniar_date', models.DateField()),
            ],
        ),
    ]
