# Generated by Django 5.0.1 on 2024-01-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_webiniar'),
    ]

    operations = [
        migrations.AddField(
            model_name='webiniar',
            name='Webiniar_description_long',
            field=models.TextField(null=True),
        ),
    ]
