# Generated by Django 5.0.1 on 2024-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0008_webiniar_webiniar_description_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('years_of_trading_experience', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('years_of_trading_experience', models.CharField(max_length=3)),
            ],
        ),
    ]
