# Generated by Django 5.0.1 on 2024-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0010_webinarregisteration_webinar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregisteration',
            name='date_of_registeration',
            field=models.CharField(default='31012024', max_length=20),
        ),
    ]
