# Generated by Django 5.0.1 on 2024-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0011_webinarregisteration_date_of_registeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_of_joined',
            field=models.CharField(default='31012024', max_length=20),
        ),
    ]
