# Generated by Django 5.0.1 on 2024-01-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0012_community_date_of_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregisteration',
            name='Webinar_author',
            field=models.CharField(default='not able to get', max_length=20),
        ),
        migrations.AddField(
            model_name='webinarregisteration',
            name='Webinar_time',
            field=models.CharField(default='31012024', max_length=20),
        ),
    ]
