# Generated by Django 5.0.1 on 2024-01-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0013_webinarregisteration_webinar_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='Communitie',
        ),
    ]
