# Generated by Django 5.0.1 on 2024-02-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0014_rename_community_communitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregisteration',
            name='parmas',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='communitie',
            name='date_of_joined',
            field=models.CharField(default='01022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='Webinar_time',
            field=models.CharField(default='01022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='date_of_registeration',
            field=models.CharField(default='01022024', max_length=20),
        ),
    ]
