# Generated by Django 5.0.1 on 2024-02-01 06:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0016_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
