# Generated by Django 5.0.1 on 2024-02-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0019_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_image',
            field=models.ImageField(upload_to='Blogs/'),
        ),
    ]
