# Generated by Django 5.0.1 on 2024-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0020_alter_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatweoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='what_we_offer/')),
                ('Title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
