# Generated by Django 5.0.1 on 2024-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0023_leads_years_of_trading_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='parmas',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
