# Generated by Django 5.0.1 on 2024-02-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0025_leads_date_of_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leads',
            new_name='Lead',
        ),
    ]
