# Generated by Django 5.0.1 on 2024-02-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0026_rename_leads_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='parmas',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='years_of_trading_experience',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitie',
            name='date_of_joined',
            field=models.CharField(default='03022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_joined',
            field=models.CharField(default='03022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='Webinar_time',
            field=models.CharField(default='03022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='date_of_registeration',
            field=models.CharField(default='03022024', max_length=20),
        ),
    ]
