# Generated by Django 5.0.1 on 2024-02-05 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0027_contact_parmas_contact_years_of_trading_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatweoffer',
            name='long_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitie',
            name='date_of_joined',
            field=models.CharField(default='05022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_joined',
            field=models.CharField(default='05022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='Webinar_time',
            field=models.CharField(default='05022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='date_of_registeration',
            field=models.CharField(default='05022024', max_length=20),
        ),
    ]
