# Generated by Django 5.0.1 on 2024-02-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0030_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitie',
            name='date_of_joined',
            field=models.CharField(default='07022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_joined',
            field=models.CharField(default='07022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='Webinar_time',
            field=models.CharField(default='07022024', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinarregisteration',
            name='date_of_registeration',
            field=models.CharField(default='07022024', max_length=20),
        ),
    ]
