# Generated by Django 5.0.1 on 2024-02-07 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0031_alter_communitie_date_of_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_descriptions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
