# Generated by Django 5.0.1 on 2024-02-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0032_course_course_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_descriptions',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='backends.course')),
            ],
        ),
    ]
