# Generated by Django 5.0.1 on 2024-02-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0034_alter_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
