# Generated by Django 5.0.1 on 2024-02-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0037_course_whatsapp_link_course_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about_instructor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThisClassFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_class_fors', to='backends.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_contents', to='backends.webinar')),
            ],
        ),
    ]
