# Generated by Django 5.0.1 on 2024-02-07 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0038_webinar_thisclassfor_dynamiccontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='Author_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
