# Generated by Django 5.0.1 on 2024-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0039_webinar_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='image',
            field=models.ImageField(upload_to='webinar'),
        ),
    ]
