# Generated by Django 5.0.1 on 2024-02-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0040_alter_webinar_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicContent',
            new_name='What_you_learn',
        ),
    ]
