# Generated by Django 5.0.1 on 2024-02-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0041_rename_dynamiccontent_what_you_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisclassfor',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_class_for', to='backends.webinar'),
        ),
        migrations.AlterField(
            model_name='what_you_learn',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='What_you_learn', to='backends.webinar'),
        ),
    ]
