# Generated by Django 5.0.1 on 2024-02-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0042_alter_thisclassfor_webinar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webiniar',
        ),
    ]
