# Generated by Django 5.0.1 on 2024-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0043_delete_webiniar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestructure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
