# Generated by Django 5.0.1 on 2024-02-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0044_alter_coursestructure_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStructure',
        ),
    ]
