# Generated by Django 5.0.1 on 2024-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0045_delete_coursestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
