# Generated by Django 5.0.1 on 2024-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0048_course_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='paytment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
